Newsweek home page clone
BrianSammit/Newsweek pull request #2
Opened 2020-08-24 23:04 UTC by Blaise-Shyaka

In this project, we have done the following:

- We set up linters
- We imported bootstrap CDN
- We wrote the markup for the page
- We styled the page using bootstrap classes
- We used a different CSS file to customize the bootstrap classes

2020-08-24 23:44 UTC, kevcap requested changes
# [STATUS] CHANGES REQUIRED♻️

#### Woah, that's a good project 🤩! (One of the best I've ever seen and I mean it!) I liked it a lot, it matches mostly the requirements and breaks my heart to not approve it 😕. But I'm sure you both can easily improve that changes 💪 😎:


_Note_: That changes marked as [OPTIONAL] are not required to approve your project, but I strongly recommend that you guys go for that extra mile, in order to get more knowledge and have a better project to add at your portfolio.

## [REQUIRED CHANGES]
#### Good practices REQUIREMENTS (Those changes to make you code like a pro 👽)⤵
- [x] Files not related to the project should not be committed and added to .gitignore (e.g. .DS_Store, package-lock.json) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/gitignore.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
- [x] Kindly remember to remove all the unnecessarily repeated CSS code. Keeping your code DRY is an excellent practice that will help you a lot and make your code more professional. (Check this link form better understanding [Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)
Take a look at this example:
![image](https://user-images.githubusercontent.com/56762529/90803794-a914df80-e2ef-11ea-9be0-40267c665254.png)
Your HTML will be something like this: 
![image](https://user-images.githubusercontent.com/56762529/90803950-e7120380-e2ef-11ea-8221-5d5d3a13e033.png)
Apply the same logic above in **ALL** those repeated rules listed below:
![image](https://user-images.githubusercontent.com/56762529/91105478-8d3e7000-e646-11ea-9fa7-e0b78a0eac58.png)
- [x] Please remove all the inline styling [Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)

#### Clone REQUIREMENTS 👥 (Those adjusts to make your page really look like the real one)⤵
- [x] The desktop and Ipad version don't have some sections (U.S., World, Business, Tech & Science, Culture, Sports, so on); I know you guys did it because I can see it at the mobile version, there's an issue with the breakpoints, take care of that team! 😎;
- [x] Check and improve the size of the Subscribe and NEWSLETTER section;
![image](https://user-images.githubusercontent.com/56762529/91105994-f4105900-e647-11ea-9990-221f2ad86524.png)


## [OPTIONAL CHANGES]
- [x] Encourage you guys to use the `<main>` tag for the dominant content of the `<body>` of a document
- [x] Add the title of the video to the title of the page; (Newsweek - News, Analysis, Politics, Business, Technology)

## Summary
✨ Well done adding a favicon! 👏
✨ Your CSS looks very clean, organized, and professional! 🎨
✨ Overall your page looks almost identical congrats! 👌
✨ You guys have an eye to details and for sure got my attention, I'll keep my eyes on you! Keep up the good work! 🥇
🔧 Just have to implement that minor changes listed above, and I know that It will be easy for you both! 

### Please make the required changes and resubmit for a new code review once you are ready💪
<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif">

## As always, I wish you @Blaise-Shyaka and @BrianSammit the very best and see you both at the top🚀

👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question about this review? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> <img  alt="gmail"  src="https://img.shields.io/badge/gmail-%20- green?logo=gmail&style=social"></a> [![Twitter Follow](https://img.shields.io/twitter/follow/kevinnnmn?style=social)](https://twitter.com/intent/follow?screen_name=kevinnnmn) [![](https://img.shields.io/badge/Slack-Kevin%20Alves-green?logo=slack&style=social)](https://microverse-students.slack.com/team/UT86D3AP4)

2020-08-24 23:44 UTC, kevincappuccino commented on index.html
> +                  style="width: 64px; height: 64px;"
- [ ] Please remove the inline styling [Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)

2020-08-24 23:44 UTC, kevincappuccino commented on index.html
> +                  style="width: 64px; height: 64px;"
- [ ] Please remove the inline styling [Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)

2020-08-24 23:44 UTC, kevincappuccino commented on index.html
> +                  style="width: 64px; height: 64px;"
- [ ] Please remove the inline styling [Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)

2020-08-24 23:44 UTC, kevincappuccino commented on index.html
> +                  style="width: 64px; height: 64px;"
- [ ] Please remove the inline styling [Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)

2020-08-24 23:44 UTC, kevincappuccino commented on index.html
> +                  style="width: 64px; height: 64px;"
- [ ] Please remove the inline styling [Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)

2020-08-24 23:44 UTC, kevincappuccino commented on index.html
> +                  style="width: 64px; height: 64px;"
- [ ] Please remove the inline styling [Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)

2020-08-24 23:44 UTC, kevincappuccino commented on index.html
> +                  style="width: 64px; height: 64px;"
- [ ] Please remove the inline styling [Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)

2020-08-24 23:44 UTC, kevincappuccino commented on index.html
> +                  style="width: 64px; height: 64px;"
- [ ] Please remove the inline styling [Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)

2020-08-24 23:44 UTC, kevincappuccino commented on index.html
> +                  style="width: 95px; height: 95px;"
- [ ] Please remove the inline styling [Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)

2020-08-24 23:44 UTC, kevincappuccino commented on index.html
> +                  style="width: 95px; height: 95px;"
- [ ] Please remove the inline styling [Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)

2020-08-24 23:44 UTC, kevincappuccino commented on index.html
> +                  style="width: 95px; height: 95px;"
- [ ] Please remove the inline styling [Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)

2020-08-24 23:44 UTC, kevincappuccino commented on index.html
> +                  style="width: 95px; height: 95px;"
- [ ] Please remove the inline styling [Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)

2020-08-25 20:07 UTC, MuriloRoque approved these changes
# Status: Approved :green_circle: 

## Hello @Blaise-Shyaka and @BrianSammit :wave: 

## :clap: :clap: :clap: 

## I have no words, you guys are amazing, congratulations!

## You may merge, good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2020-08-25 20:51 UTC, merged